<?php

/**
 * Implementation of hook_block_info().
 */
function footer_blocks_block_info() {
  $blocks['footer-brand'] = array(
    'info' => t('Footer Brand'),
  );
  $blocks['footer-message'] = array(
    'info' => t('Footer Message'),
  );
  
  return $blocks;
}

/**
 * Implementation of hook_block_view().
 */
function footer_blocks_block_view($delta='') {
  $block = array();
  switch ($delta) {
    case 'footer-brand':
      $block['content'] = footer_brand_contents();
      break;
    case 'footer-message':
      $block['content'] = footer_message_contents();
      break;
  }
  return $block;
}

 /**
 * custom html block
 * @return string
 */
function footer_brand_contents() {
  return '
    <div class="footer-brand">
      <a class="footer-brand-logo" style="border-bottom: none;" href="http://www.ucmerced.edu">UC Merced</a>
      <p>The first new American research university in the 21<sup>st</sup> century, with a mission of research, teaching and service.</p>
    </div><!-- /footer-brand -->
  ';
}

function footer_message_contents() {
  return '
  <div class="footer-info">
    <p><a href="http://www.ucmerced.edu">University of California</a>, Merced 5200 North Lake Rd. Merced, CA 95343 T: (209) 228-4400 <span class="right">&copy; 2010 <a href="http://www.universityofcalifornia.edu/regents/">UC Regents</a> | <a href="http://www.ucmerced.edu/privacylegal.asp">Privacy/Legal</a></span></p>
  </div><!-- /footer-info -->
  ';
}