<?php

/**
 * Implementation of hook_block_info().
 */
function ucm_footer_blocks_block_info() {
  $blocks['brand'] = array(
    'info' => t('Bottom Brand'),

  );
  $blocks['bottom-info'] = array(
    'info' => t('Bottom Information'),
  );

  $blocks['bottom-required-links'] = array(
    'info' => t('Bottom Required Links'),
  );
  
  return $blocks;
}

/**
 * Implementation of hook_block_view().
 */
function ucm_footer_blocks_block_view($delta='') {
  $block = array();
  switch ($delta) {
    case 'brand':
      $block['content'] = brand_contents();
      break;
    case 'bottom-info':
      $block['content'] = bottom_info_contents();
      break;
    case 'bottom-required-links':
      $block['subject'] = t('Resources');
      $block['content'] = bottom_required_links_contents();
      break;
  }
  return $block;
}

 /**
 * custom html block
 * @return string
 */
function brand_contents() {
  return '
    <div class="footer-brand">
      <a class="footer-brand-logo" style="border-bottom: none;" href="http://www.ucmerced.edu">UC Merced</a>
      <p>The first new American research university in the 21<sup>st</sup> century, with a mission of research, teaching and service.</p>
    </div><!-- /footer-brand -->
  ';
}

function bottom_info_contents() {
  return '
  <div class="footer-info">
    <p><a href="http://www.ucmerced.edu">University of California</a>, Merced 5200 North Lake Rd. Merced, CA 95343 T: (209) 228-4400 <span class="right">&copy; 2010 <a href="http://www.universityofcalifornia.edu/regents/">UC Regents</a> | <a href="http://www.ucmerced.edu/privacylegal.asp">Privacy/Legal</a></span></p>
  </div><!-- /footer-info -->
  ';
}

function bottom_required_links_contents() {
  return '
  <div class="footer-required-links">
    <ul class="menu">
      <li><a href="http://www.ucmerced.edu/site-list" target="_blank">Site List</a></li>
      <li><a href="http://directory.ucmerced.edu/" target="_blank">Directory</a></li>
      <li><a href="http://www.ucmerced.edu/directions-map" target="_blank">Directions &amp; Map</a></li>
      <li><a href="http://www.ucmerced.edu/about-uc-merced" target="_blank">About UC Merced</a></li>
      <!-- li><a href="#" target="_blank">Site Content</a></li -->
    </ul>
  </div><!-- /footer-required-links -->
  ';
}