<?php

/**
 * Implementation of hook_block_info().
 */
function ucm_footer_blocks_block_info() {
  $blocks['brand'] = array(
    'info' => t('Bottom Brand'),

  );
  $blocks['bottom-info'] = array(
    'info' => t('Bottom Information'),
  );
  
  return $blocks;
}

/**
 * Implementation of hook_block_view().
 */
function ucm_footer_blocks_block_view($delta='') {
  $block = array();
  switch ($delta) {
    case 'brand':
      $block['content'] = brand_contents();
      break;
    case 'bottom-info':
      $block['content'] = bottom_info_contents();
      break;
  }
  return $block;
}

/**
*Implements hook_block_info_alter().
*/
function ucm_footer_blocks_block_info_alter(&$blocks, $theme, $code_blocks) {
  if ($theme == "inception"){
    dsm($blocks);
    $blocks['ucm_footer_blocks']['brand']['region'] = 'footer';
    $blocks['ucm_footer_blocks']['bottom-info']['region'] = 'footer_message';
    $blocks['ucm_footer_blocks']['brand']['status'] = 1;
    $blocks['ucm_footer_blocks']['bottom-info']['status'] = 1;
  }
}

 /**
 * custom html block
 * @return string
 */
function brand_contents() {
  return '
    <div class="footer-brand">
      <a class="footer-brand-logo" style="border-bottom: none;" href="http://www.ucmerced.edu">UC Merced</a>
      <p>The first new American research university in the 21<sup>st</sup> century, with a mission of research, teaching and service.</p>
    </div><!-- /footer-brand -->
  ';
}

function bottom_info_contents() {
  return '
  <div class="footer-info">
    <p><a href="http://www.ucmerced.edu">University of California</a>, Merced 5200 North Lake Rd. Merced, CA 95343 T: (209) 228-4400 <span class="right">&copy; 2010 <a href="http://www.universityofcalifornia.edu/regents/">UC Regents</a> | <a href="http://www.ucmerced.edu/privacylegal.asp">Privacy/Legal</a></span></p>
  </div><!-- /footer-info -->
  ';
}